---
name: tfplus-pre-commit
description: run pre-commit to check codes for tfplus
runs:
  using: 'docker'
  image: "easydl/tfplus:tf213_dev"
  args:
    - "/bin/bash"
    - "-c"
    - "cd tfplus \
&& sh run_tfplus_precommit.sh"
