---
name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      # This step references the directory that contains the action.
      - uses: ./.github/actions/pre-commit
  dlrover-python-test:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - name: checkout branch
        uses: actions/checkout@v3
      # This step references the directory that contains the action.
      - name: RUN pytest
        uses: ./.github/actions/dlrover-python-test
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  operator-test:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      # This step references the directory that contains the action.
      - name: RUN gotest
        uses: ./.github/actions/operator-test
  brain-test:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      # This step references the directory that contains the action.
      - uses: ./.github/actions/brain-test
  dlrover-system-test-criteo-deeprec:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      # This step references the directory that contains the action.
      - uses: ./.github/actions/dlrover-system-test-criteo-deeprec
  dlrover-system-test-deepfm:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      # This step references the directory that contains the action.
      - uses: ./.github/actions/dlrover-system-test-deepfm
  dlrover-system-test-tf2:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      # This step references the directory that contains the action.
      - uses: ./.github/actions/dlrover-system-test-tf2
  atorch-python-test:
    runs-on: self-hosted
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
        with:
          clean: false
      # This step references the directory that contains the action.
      - uses: ./.github/actions/atorch-python-test
  atorch-pre-commit:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      # This step references the directory that contains the action.
      - uses: ./.github/actions/atorch-pre-commit
  tfplus-python-test:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: checkout
        uses: actions/checkout@v3
      # Check if there are changes in the 'tfplus' directory
      - name: check for changes in 'tfplus'
        id: check_files
        run: |
          git fetch origin main
          FILES=$(git diff --name-only origin/main)
          if echo "$FILES" | grep -q "tfplus/"; then
            echo "::set-output name=run_job::true"
          else
            echo "::set-output name=run_job::false"
          fi
      # Only run the tests if there are changes in the 'tfplus' directory
      - name: Run tfplus tests
        if: steps.check_files.outputs.run_job == 'true'
        uses: ./.github/actions/tfplus-python-test
  tfplus-pre-commit:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      # This step references the directory that contains the action.
      - uses: ./.github/actions/tfplus-pre-commit
